server:
  port: 8000
spring:
  application:
    name: Img
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: 账号
    password: 密码
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    # customer01
    url: jdbc:p6spy:mysql://数据库地址:3306/manage?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
mybatis-plus:
  # 指定别名扫描路径，这个路径后续在client-common模块里定义，该路径下的实体类将自动配置别名，默认为类名首字母小写。配置别名后，便可以直接在MyBatis XML文件里使用了
  type-aliases-package: com.source.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 指定为null，否则再插入空值时会报“无效的列类型”错误；
    jdbc-type-for-null: null
  global-config:
    # 设置为false关闭MyBatis Plus Banner打印
    banner: false

# minio
minio:
  # URL地址(默认是9000端口)
  endPoint: xx
  # 账号
  accessKey: xx
  # 密码
  secretKey: xx
  # 桶名
  bucketName: img
  # 文件分片上传限制
  partSize: 104857600
  # 图片反问地址
  imgUrl: xx